# Generated by Django 5.0.6 on 2024-07-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_certification_date_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.CharField(default=-1995, max_length=100),
            preserve_default=False,
        ),
    ]
